<?php

namespace AppBundle\Repository;

/**
 * BloggerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloggerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
