sonata_admin:
    security:

        # the default value
#        handler: sonata.admin.security.handler.role

        # use this service if you want ACL
        handler: sonata.admin.security.handler.acl
        
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [VIEW, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]

#        # permissions not related to an object instance and also to be available when objects do not exist
#        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
#
#        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      Admin Dashboard
    title_logo: /bundles/sonataadmin/logo_title.png
    options:
        html5_validate:       true

        # Auto order groups and admins by label or id
        sort_admins:          false
        confirm_exit:         true
        use_select2:          true
        use_icheck:           true
        use_bootlint:         false
        use_stickyforms:      true
#        pager_links:          1
        form_type:            standard
        dropdown_number_groups_per_colums:  2
        title_mode:         both                # or "single_text"; "single_image"

        # Enable locking when editing an object, if the corresponding object manager supports it.
        lock_protection:      false

    templates:
        # default global templates
 
        layout:                         SonataAdminBundle::layout.html.twig 
#        layout:                         SonataAdminBundle::standard_layout.html.twig
        ajax:                           SonataAdminBundle::ajax_layout.html.twig
        list:                           SonataAdminBundle:CRUD:list.html.twig
        show:                           SonataAdminBundle:CRUD:show.html.twig
        show_compare:                   SonataAdminBundle:CRUD:show_compare.html.twig
        edit:                           SonataAdminBundle:CRUD:edit.html.twig
        history:                        SonataAdminBundle:CRUD:history.html.twig
        preview:                        SonataAdminBundle:CRUD:preview.html.twig
        delete:                         SonataAdminBundle:CRUD:delete.html.twig
        batch:                          SonataAdminBundle:CRUD:list__batch.html.twig
        acl:                            SonataAdminBundle:CRUD:acl.html.twig
        action:                         SonataAdminBundle:CRUD:action.html.twig
        select:                         SonataAdminBundle:CRUD:list__select.html.twig
        filter:                         SonataAdminBundle:Form:filter_admin_fields.html.twig
        dashboard:                      SonataAdminBundle:Core:dashboard.html.twig
        search:                         SonataAdminBundle:Core:search.html.twig
        batch_confirmation:             SonataAdminBundle:CRUD:batch_confirmation.html.twig
        inner_list_row:                 SonataAdminBundle:CRUD:list_inner_row.html.twig
        
        base_list_field:                SonataAdminBundle:CRUD:base_list_field.html.twig
        list_block:                     SonataAdminBundle:Block:block_admin_list.html.twig
#        user_block:                     SonataAdminBundle:Core:user_block.html.twig
        add_block:                      SonataAdminBundle:Core:add_block.html.twig
        pager_links:                    SonataAdminBundle:Pager:links.html.twig
        pager_results:                  SonataAdminBundle:Pager:results.html.twig
        tab_menu_template:              SonataAdminBundle:Core:tab_menu_template.html.twig
        history_revision_timestamp:     SonataAdminBundle:CRUD:history_revision_timestamp.html.twig
        short_object_description:       SonataAdminBundle:Helper:short-object-description.html.twig
        search_result_block:            SonataAdminBundle:Block:block_search_result.html.twig
        action_create:                  SonataAdminBundle:CRUD:dashboard__action_create.html.twig
        button_acl:                     SonataAdminBundle:Button:acl_button.html.twig
        button_create:                  SonataAdminBundle:Button:create_button.html.twig
        button_edit:                    SonataAdminBundle:Button:edit_button.html.twig
        button_history:                 SonataAdminBundle:Button:history_button.html.twig
        button_list:                    SonataAdminBundle:Button:list_button.html.twig
        button_show:                    SonataAdminBundle:Button:show_button.html.twig
    
    assets:
        stylesheets:

            # Defaults:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.css                                   ###skin css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - bundles/sonataadmin/css/colors.css
        javascripts:

            # Defaults:
            - bundles/sonatacore/vendor/jquery/dist/jquery.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonatacore/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jquery-form/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonatacore/vendor/select2/select2.min.js
            - bundles/sonataadmin/vendor/admin-lte/dist/js/app.min.js
            - bundles/sonataadmin/vendor/iCheck/icheck.min.js
            - bundles/sonataadmin/vendor/slimScroll/jquery.slimscroll.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/jquery.waypoints.min.js
            - bundles/sonataadmin/vendor/waypoints/lib/shortcuts/sticky.min.js
            - bundles/sonataadmin/Admin.js
            - bundles/sonataadmin/treeview.js
        
        
        
##########################################                     blocks                       ############################################################        

    dashboard:
        groups:
            Busshike.clinic:
                keep_open:            true
                label:           My Clinic
                label_catalogue: BusshikeClinicBundle
                icon:            '<i class="fa fa-user-md"></i>'
                items:
 
                    - admin.patients
                    - admin.appointments
                    - tutorial.blog.admin.post
                    - tutorial.blog.admin.tag
                    - tutorial.blog.admin.comment
                    
            App.admin.group.custom:
                keep_open:            true
                label:           My Content
                label_catalogue: AppBundle
                icon:            '<i class="fa fa-archive"></i>'
                items:
#                    
                    - admin.bloggertype
                    - admin.blogger 
                    
                     
                    
            sonata.admin.group.content:
                label:           sonata_content
                label_catalogue: SonataDemoBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - sonata.news.admin.comment
                    - sonata.news.admin.post
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
                     
#                    - sonata.comment.admin.thread

#            sonata.admin.group.ecommerce:
#                label:           sonata_ecommerce
#                label_catalogue: SonataAdminBundle
#                icon:            '<i class="fa fa-dollar"></i>'
#                items:
#                    - sonata.customer.admin.customer
#                    - sonata.invoice.admin.invoice
#                    - sonata.order.admin.order
#                    - sonata.product.admin.product

            sonata.admin.group.classification:
                label:           sonata_classification
                label_catalogue: SonataClassificationBundle
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context

#            sonata.admin.group.site_builder:
#                label:           Site Builder
#                label_catalogue: SonataDemoBundle
#                icon:            '<i class="fa fa-puzzle-piece"></i>'
#                items:
#                    - sonata.page.admin.page
#                    - sonata.page.admin.site

            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
#                    - sonata.page.admin.site
                    - sonata.notification.admin.message

#            sonata.admin.group.demo:
#                label: Demo
#                icon:  '<i class="fa fa-play-circle"></i>'
#                items:
#                    - sonata.demo.admin.car
#                    - sonata.demo.admin.engine
#                    - sonata.demo.admin.color
#                    - sonata.demo.admin.material
                    
                    
        blocks:
            
                        
            -
                class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  sonata.user.admin.group    # admin code - service id
                    icon:  fa fa-users                  # font awesome icon
                    text:  Total Groups
                    color: bg-blue                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        edited: { value: 1 }            
            
            -
                class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  sonata.news.admin.post    # admin code - service id
                    icon:  fa fa-newspaper-o                 # font awesome icon
                    text:  Total Blogs/Posts
                    color: bg-green                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        edited: { value: 1 }            
            
            -
                class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  sonata.user.admin.user    # admin code - service id
                    icon:  fa fa-users                  # font awesome icon
                    text:  Total Users
                    color: bg-yellow                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        edited: { value: 1 }
                        
            -
                class:    col-lg-3 col-xs-6          # twitter bootstrap responsive code
                position: top                        # zone in the dashboard
                type:     sonata.admin.block.stats   # block id
                settings:
                    code:  sonata.news.admin.comment    # admin code - service id
                    icon:  fa fa-comments-o                 # font awesome icon
                    text:  Total Comments
                    color: bg-red                 # colors: bg-green, bg-red and bg-aqua
                    filters:                         # filter values
                        edited: { value: 1 }            
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

            # Customize this part to add new block configuration
             
            - { position: center, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 5, mode: public }}
            - { position: center, type: sonata.news.block.recent_comments, settings: { title: Recent Comments, number: 5, mode: public }}
            - { position: right, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 25, icon: '<i class="fa fa-flag-o fa-fw"></i>',  title: "My Timeline Block" }}
            - { position: right, type: sonata.block.service.text, settings: { content: "<h2>Welcome to the Sonata Admin</h2> <p>This is a <code>sonata.block.service.text</code> from the Block Bundle, you can create and add new block in these area by configuring the <code>sonata_admin</code> section.</p> <br /> For instance, here a RSS feed parser (<code>sonata.block.service.rss</code>):"} }
            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: http://sonata-project.org/blog/archive.rss }}
            
            
            
            
            
            
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.search_result:
            contexts: [admin]
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.stats:
            
        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
         
        # Some specific block from the SonataMediaBundle
        sonata.media.block.media:
        sonata.media.block.gallery:
        sonata.media.block.feature_media:
        sonata.timeline.block.timeline:
# ///////////////    news block    ///////////////             
        sonata.news.block.recent_posts:
        sonata.news.block.recent_comments:
# ///////////////    user block    ///////////////            
        sonata.user.block.menu:
        sonata.user.block.account:
            
#//////////////      social /////////////////////
        
        sonata.seo.block.social.container:
        sonata.seo.block.email.share_button:
        sonata.seo.block.facebook.like_box:
        sonata.seo.block.facebook.like_button:
        sonata.seo.block.facebook.send_button:
        sonata.seo.block.facebook.share_button:
        sonata.seo.block.twitter.share_button:
        sonata.seo.block.twitter.follow_button:
        sonata.seo.block.twitter.hashtag_button:
        sonata.seo.block.twitter.mention_button:
        sonata.seo.block.twitter.embed:
        sonata.seo.block.pinterest.pin_button:
        
        