<?php

namespace Busshike\ClinicBundle\Repository;

/**
 * PatientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientsRepository extends \Doctrine\ORM\EntityRepository
{
}
